# Generated by Django 6.1.1 on 2026-09-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('specialization', models.CharField(help_text='e.g. Electrical Systems, Plumbing, HVAC, Wi-Fi/Network, Carpentry', max_length=100)),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('On Leave', 'On Leave')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Maintenance Staff',
                'verbose_name_plural': 'Maintenance Staff',
                'ordering': ['name'],
            },
        ),
    ]
